# daemon/lessons.py
"""S31-4 lesson review gate — the human checkpoint between mining and the wiki.

A wrong lesson is worse than no lesson, so nothing the miner produces reaches
``lessons/`` without passing through here:

- **promote** moves a draft into ``lessons/`` (maturity seed → sapling) and marks
  it ``review: approved``;
- **reject** moves it to ``_working/sessions/rejected/`` and *stores the reason*,
  which :func:`daemon.miner.collect_rejection_reasons` injects into the next
  mining prompt for that project. That feedback loop is what replaces the
  never-built ``daemon/validate_write.py`` duplicate guard;
- **corroborate** bumps an existing lesson's corroboration count and links the
  new session instead of writing a near-duplicate page.

Only the promote path writes into ``lessons/``. Everything else is best-effort
filesystem work that reports failures rather than raising.

Auto-promotion is opt-in via ``SESSION_MINING_AUTO_PROMOTE``:

- ``off`` (default) — every draft waits for a human.
- ``conservative`` — auto-promote once 2+ independent sessions corroborate it.
- ``aggressive`` — auto-promote every mined draft.

``aggressive`` is deliberately available but not the default: corroboration is
the only evidence the system has that a lesson generalises.
"""

import logging
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("vault-memoryd.lessons")

PROMOTED_DIRNAME = "lessons"
DRAFTS_DIRNAME = "_working/sessions"
REJECTED_DIRNAME = "_working/sessions/rejected"

POLICY_OFF = "off"
POLICY_CONSERVATIVE = "conservative"
POLICY_AGGRESSIVE = "aggressive"
POLICIES = (POLICY_OFF, POLICY_CONSERVATIVE, POLICY_AGGRESSIVE)

#: Independent sessions required before ``conservative`` promotes unattended.
CONSERVATIVE_MIN_CORROBORATION = 2

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
_LIST_RE = re.compile(r"^\[(.*)\]$", re.DOTALL)
# Values that would break a naive ``key: value`` line.
_NEEDS_QUOTING_RE = re.compile(r"^[\s>|#\[\]{}&*!%@`\"']|:\s|\s#")


# ---------------------------------------------------------------------------
# frontmatter
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> Dict[str, str]:
    """Top-level ``key: value`` pairs, in file order.

    Deliberately not a YAML parser: drafts are generated by this codebase, and
    a hard dependency on PyYAML here would make the review gate a new install
    requirement for lite mode.
    """
    match = _FRONTMATTER_RE.match(text or "")
    if not match:
        return {}
    out: Dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or line.startswith((" ", "\t")):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        out[key.strip()] = _unquote(value.strip())
    return out


def split_frontmatter(text: str) -> tuple[Dict[str, str], str]:
    """``(frontmatter, body)`` — body keeps no leading newline padding.

    Draft files conventionally have a blank line between ``---`` and the body;
    normalising it here keeps :meth:`Draft.render` from growing the gap every
    time a draft is rewritten (corroboration, review).
    """
    match = _FRONTMATTER_RE.match(text or "")
    if not match:
        return {}, (text or "")
    return parse_frontmatter(text), text[match.end():].lstrip("\n")


def _format_scalar(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\r", " ").replace("\n", " ").strip()
    # A ``[a, b]`` value is a list, not a string that happens to start with a
    # bracket — quoting it here would make every round-trip lossy.
    if _LIST_RE.match(text):
        return text
    if text == "" or _NEEDS_QUOTING_RE.search(text):
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


def _unquote(value: str) -> str:
    """Reverse :func:`_format_scalar`'s quoting for a parsed value."""
    if len(value) >= 2 and value.startswith('"') and value.endswith('"'):
        return value[1:-1].replace('\\"', '"')
    if len(value) >= 2 and value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    return value


def render_frontmatter(frontmatter: Dict[str, Any]) -> str:
    lines = ["---"]
    for key, value in frontmatter.items():
        if isinstance(value, (list, tuple)):
            lines.append(key + ": [" + ", ".join(str(v) for v in value) + "]")
        else:
            lines.append(key + ": " + _format_scalar(value))
    lines.append("---")
    return "\n".join(lines) + "\n"


def parse_list(value: Any) -> List[str]:
    """Read ``[a, b]`` back into a list; tolerate a scalar or a blank."""
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return [str(v).strip() for v in value if str(v).strip()]
    text = str(value).strip()
    match = _LIST_RE.match(text)
    if match:
        text = match.group(1)
    return [part.strip().strip("\"'") for part in text.split(",") if part.strip()]


# ---------------------------------------------------------------------------
# drafts
# ---------------------------------------------------------------------------

@dataclass
class Draft:
    """One mined draft on disk."""

    path: Path
    slug: str
    rel_path: str
    frontmatter: Dict[str, str] = field(default_factory=dict)
    body: str = ""

    @property
    def title(self) -> str:
        return self.frontmatter.get("title") or self.slug

    @property
    def review(self) -> str:
        return (self.frontmatter.get("review") or "pending").lower()

    @property
    def project(self) -> Optional[str]:
        return self.frontmatter.get("project") or None

    @property
    def kind(self) -> str:
        return (self.frontmatter.get("type") or "lesson").lower()

    @property
    def corroboration(self) -> int:
        raw = self.frontmatter.get("corroboration")
        try:
            return int(raw) if raw not in (None, "") else 1
        except (TypeError, ValueError):
            return 1

    @property
    def sessions(self) -> List[str]:
        return parse_list(self.frontmatter.get("sessions"))

    @property
    def entities(self) -> List[str]:
        """Wikilinked entities in the body — the lint conflict surface."""
        return re.findall(r"\[\[([^\]|#]+)", self.body or "")

    def render(self) -> str:
        body = (self.body or "").lstrip("\n")
        return render_frontmatter(self.frontmatter) + "\n" + body


def parse_draft(path: Path, vault_root: Path) -> Optional[Draft]:
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        logger.warning("could not read draft %s: %s", path, e)
        return None
    frontmatter, body = split_frontmatter(text)
    try:
        rel = str(Path(path).resolve().relative_to(Path(vault_root).resolve()))
    except (ValueError, OSError):
        rel = str(path)
    return Draft(path=Path(path), slug=Path(path).stem, rel_path=rel, frontmatter=frontmatter, body=body)


def _candidate_dirs(vault_root: Path) -> List[Path]:
    root = Path(vault_root)
    return [root / DRAFTS_DIRNAME, root / PROMOTED_DIRNAME]


def list_drafts(
    vault_root: Path,
    *,
    review: Optional[str] = "pending",
    project: Optional[str] = None,
) -> List[Draft]:
    """Drafts on disk, oldest filename first. ``review=None`` returns all."""
    found: List[Draft] = []
    for directory in _candidate_dirs(vault_root):
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.md")):
            draft = parse_draft(path, vault_root)
            if draft is None:
                continue
            if review is not None and draft.review != review:
                continue
            if project and draft.project and draft.project != project:
                continue
            found.append(draft)
    return found


def find_draft(vault_root: Path, name: str) -> Optional[Draft]:
    """Resolve a draft by relative path, filename stem, or title slug.

    Accepts ``_working/sessions/2026-09-12-pin-the-version.md``,
    ``2026-09-12-pin-the-version``, or ``pin-the-version`` so a caller can pass
    whatever the review surface gave them.
    """
    if not name:
        return None
    root = Path(vault_root)
    raw = str(name).strip()

    direct = (root / raw) if not Path(raw).is_absolute() else Path(raw)
    if direct.is_file():
        return parse_draft(direct, root)

    wanted = Path(raw).stem
    for directory in _candidate_dirs(root):
        if not directory.is_dir():
            continue
        path = directory / (wanted + ".md")
        if path.is_file():
            return parse_draft(path, root)

    # Fall back to a suffix match so a bare title slug finds a dated draft.
    for directory in _candidate_dirs(root):
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.md")):
            if path.stem.endswith("-" + wanted) or _slugify(path.stem) == _slugify(raw):
                return parse_draft(path, root)
    return None


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (value or "").lower()).strip("-")


def _write(path: Path, draft: Draft) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(draft.render(), encoding="utf-8")
    tmp.replace(path)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# promote / reject
# ---------------------------------------------------------------------------

def promote_draft(
    vault_root: Path,
    name: str,
    *,
    reviewer: Optional[str] = None,
) -> Dict[str, Any]:
    """Accept a draft into ``lessons/``. Returns ``{ok, ...}``; never raises."""
    root = Path(vault_root)
    draft = find_draft(root, name)
    if draft is None:
        return {"ok": False, "error": "draft not found", "name": name}

    if draft.review == "approved":
        return {"ok": True, "already_promoted": True, "path": draft.rel_path, "slug": draft.slug}

    target_dir = root / PROMOTED_DIRNAME
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / _promoted_filename(draft)

    frontmatter = dict(draft.frontmatter)
    frontmatter["review"] = "approved"
    frontmatter["reviewed_at"] = _now()
    if reviewer:
        frontmatter["reviewer"] = reviewer
    frontmatter["maturity"] = "sapling"
    frontmatter["corroboration"] = draft.corroboration
    # Approved process knowledge is still revisable; trust rises with review.
    frontmatter["trust"] = "medium" if draft.corroboration < CONSERVATIVE_MIN_CORROBORATION else "high"

    promoted = Draft(path=target, slug=target.stem, rel_path=str(target.relative_to(root)), frontmatter=frontmatter, body=draft.body)
    try:
        _write(target, promoted)
    except OSError as e:
        logger.warning("promote failed for %s: %s", name, e)
        return {"ok": False, "error": "could not write lesson", "name": name}

    # The draft's job is done; leaving it would let the miner re-corroborate a
    # lesson that is already in the wiki.
    try:
        if draft.path.parent.name != PROMOTED_DIRNAME:
            draft.path.unlink()
    except OSError as e:
        logger.warning("promoted %s but could not remove the draft: %s", target, e)

    return {
        "ok": True,
        "slug": promoted.slug,
        "path": promoted.rel_path,
        "title": promoted.title,
        "corroboration": promoted.corroboration,
    }


def _promoted_filename(draft: Draft) -> str:
    """``lessons/{slug}.md``, stripping the miner's ``YYYY-MM-DD-`` prefix."""
    stem = re.sub(r"^\d{4}-\d{2}-\d{2}-", "", draft.slug)
    return (stem or draft.slug) + ".md"


def reject_draft(
    vault_root: Path,
    name: str,
    reason: str,
    *,
    reviewer: Optional[str] = None,
) -> Dict[str, Any]:
    """Reject a draft and remember *why*. The reason feeds the next mining prompt."""
    root = Path(vault_root)
    draft = find_draft(root, name)
    if draft is None:
        return {"ok": False, "error": "draft not found", "name": name}

    reason = " ".join((reason or "").split())
    if not reason:
        return {"ok": False, "error": "a rejection reason is required", "name": name}

    frontmatter = dict(draft.frontmatter)
    frontmatter["review"] = "rejected"
    frontmatter["rejection_reason"] = reason
    frontmatter["rejected_at"] = _now()
    if reviewer:
        frontmatter["reviewer"] = reviewer

    target_dir = root / REJECTED_DIRNAME
    target = target_dir / draft.path.name

    rejected = Draft(path=target, slug=draft.slug, rel_path=str(target.relative_to(root)), frontmatter=frontmatter, body=draft.body)
    try:
        _write(target, rejected)
        if draft.path != target:
            draft.path.unlink()
    except OSError as e:
        logger.warning("reject failed for %s: %s", name, e)
        return {"ok": False, "error": "could not record the rejection", "name": name}

    return {"ok": True, "slug": draft.slug, "path": rejected.rel_path, "reason": reason}


# ---------------------------------------------------------------------------
# corroboration
# ---------------------------------------------------------------------------

def corroborate(vault_root: Path, name: str, session_id: Optional[str] = None) -> Optional[Dict[str, Any]]:
    """Bump an existing lesson's corroboration and link the new session.

    Returns ``None`` when there is nothing to corroborate — the caller treats
    that as "write a new draft" rather than as an error.
    """
    root = Path(vault_root)
    draft = find_draft(root, name)
    if draft is None:
        return None

    sessions = draft.sessions
    already = bool(session_id) and session_id in sessions
    if not already:
        if session_id:
            sessions.append(session_id)
        frontmatter = dict(draft.frontmatter)
        frontmatter["corroboration"] = str(draft.corroboration + 1) if session_id else str(draft.corroboration)
        frontmatter["last_corroborated_at"] = _now()
    else:
        frontmatter = dict(draft.frontmatter)

    frontmatter["sessions"] = sessions
    updated = Draft(path=draft.path, slug=draft.slug, rel_path=draft.rel_path, frontmatter=frontmatter, body=draft.body)
    try:
        _write(draft.path, updated)
    except OSError as e:
        logger.warning("corroboration write failed for %s: %s", name, e)
        return None

    return {
        "slug": updated.slug,
        "path": updated.rel_path,
        "corroboration": updated.corroboration,
        "sessions": sessions,
        "already_linked": already,
    }


# ---------------------------------------------------------------------------
# auto-promotion
# ---------------------------------------------------------------------------

def auto_promote_policy() -> str:
    """``SESSION_MINING_AUTO_PROMOTE`` ∈ off | conservative | aggressive."""
    raw = (os.getenv("SESSION_MINING_AUTO_PROMOTE") or POLICY_OFF).strip().lower()
    return raw if raw in POLICIES else POLICY_OFF


def should_auto_promote(draft: Draft, policy: Optional[str] = None) -> bool:
    policy = policy or auto_promote_policy()
    if policy == POLICY_AGGRESSIVE:
        return draft.review == "pending"
    if policy == POLICY_CONSERVATIVE:
        return draft.review == "pending" and draft.corroboration >= CONSERVATIVE_MIN_CORROBORATION
    return False


def apply_auto_promote(vault_root: Path, *, names: Optional[List[str]] = None) -> List[Dict[str, Any]]:
    """Promote pending drafts the configured policy already trusts."""
    policy = auto_promote_policy()
    if policy == POLICY_OFF:
        return []

    if names is None:
        candidates = list_drafts(vault_root, review="pending")
    else:
        candidates = [d for d in (find_draft(vault_root, n) for n in names) if d is not None]

    promoted = []
    for draft in candidates:
        if not should_auto_promote(draft, policy):
            continue
        result = promote_draft(vault_root, str(draft.path), reviewer="auto:" + policy)
        if result.get("ok"):
            promoted.append(result)
    return promoted
